### PR TITLE
Merge pull request #3 from kalviumcommunity/oops

### PR DESCRIPTION
**Pull request by Akanksha987**
Milestone 3 concepts
1. Inheritance
2. Dynamic Memory Allocation
Here is the explanation video link
[Link 1](https://www.loom.com/share/43afb518b2554b90be8c928e7da616ef?sid=e8b4bc1d-4c12-4a0b-8849-b6d4724753a6)
[Link 2](https://www.loom.com/share/21708553e145439abe017a1af335d887?sid=17663611-faac-4328-a683-ac852563f04f)

### CODE REVIEW

**Review by th3c0d3br34ker — APPROVED** [review]
thanks @Akanksha987 for your submission. please go ahead and merge this PR for `Inheritance`.

**Comment by th3c0d3br34ker** [comment]
hey @Akanksha987 the explanation provided for `Dynamic Memory Allocation` is incorrect. please schedule a viva for this concept.

**Comment by Akanksha987** [comment]
Sire

**Comment by th3c0d3br34ker** [comment]
Approved during viva, please go ahead and merge this PR for `Dynamic Memory Allocation`

**Review by th3c0d3br34ker — APPROVED** [review]

**Pull request merged**
